config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root to: "application#welcome"

  get "/recipes/ordered_list", to: "recipes#ordered_list"
  get "/users/:user_id/recipes" ,to: "recipes#index", as: "user_recipes"

  resources :categories do
    resources :recipes, only: [:index, :show, :new]
  end
  
  resources :recipes

  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => "callbacks" }

  devise_scope :user do 
    get "/login", to: "devise/sessions#new"
    get "/signup", to: "devise/registrations#new"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  has_many :users, through: :recipes

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }

   before_save { name.capitalize! }


   
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :reviews

  belongs_to :user
  belongs_to :category
  validates :title, presence: true
  # validates :title, uniqueness: true
  scope :ordered_by_title, -> { order(title: :asc) }
  accepts_nested_attributes_for :category, reject_if: :all_blank


  def category_attributes=(category_hash)
    #binding.pry
    if category_hash[:name].blank?

    else
      
     category = Category.find_or_create_by(name: category_hash[:name].capitalize)
     self.category = category

    end
    
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :heading, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :categories, through: :recipes
  has_many :reviews
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.username = auth.info.name
            user.id = auth.id
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
   
   
    def github
        
        @user = User.from_omniauth(request.env["omniauth.auth"])
        #binding.pry
        sign_in_and_redirect @user
    end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


    def index
        @categories = current_user.categories
    end

    def show
        @category = current_user.categories.find_by(params[:id])
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_recipe, only: [:edit, :update, :destroy]


    def index

        if params[:category_id]

            set_cat
            is_it_a_cat(@category)
        elsif params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @recipes = @user.recipes
        else

            @recipes = Recipe.all
        end
    end

    def new
        if params[:category_id]
            set_cat
            if @category    
                @recipe = @category.recipes.build
            else
                redirect_to new_recipe_path, alert: "recipe not found"
            end
        else  
            @recipe = current_user.recipes.build
        end
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)

        if @recipe.valid?
            @recipe.save
            redirect_to @recipe
        else
            render :new
        end 
    end

    def show
        if params[:category_id]
            @recipes = Category.find(params[:category_id]).recipes

            @recipe = @recipes.find_by(id: params[:id])

            is_it_a_recipe(@recipe) 
        else
            @recipe = Recipe.find_by(id: params[:id])

            is_it_a_recipe(@recipe)
        end
    end

    def ordered_list
        
        @filter = true 

        @recipes = current_user.recipes.ordered_by_title

        render :index
    end

    def edit
        is_it_a_recipe(@recipe)
    end

    def update
        
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render :edit
        end
    end

    def destroy
        @recipe.destroy
        redirect_to recipes_path, alert: "Recipe deleted"
    end

    private

    def recipe_params
        params.require(:recipe).permit(:title, :instructions, :cooking_time, :category_id, :user_id, category_attributes: [:name])
    end

    def set_recipe
        @recipe = current_user.recipes.find_by(id: params[:id])
    end

    def is_it_a_recipe(recipe)
        if !recipe
            redirect_to new_recipe_path, alert: "Recipe not found. Create a new one here." 
        end
    end

    def set_cat
        @category = Category.find_by(id: params[:category_id])
    end
    
    def is_it_a_cat(category)
        if category
            @recipes = category.recipes
        else
            redirect_to categories_path, alert: "Category not found"
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


    

    def new
        @review = current_user.reviews.build
    end

    def create
        review = current_user.reviews.build(review_params)
        if review.valid?
            review.save
            redirect_to review.recipe
        else
            redirect_to root_path
        end

    end

    def show
    end

    private

    def review_params
        params.require(:review).permit(:recipe_id, :user_id, :heading, :description )
    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/welcome.html.erb
<% if user_signed_in? %>
<p>Hi <%=current_user.username%>! Get started by creating and managing your recipes.</p><br>

<% else%>
<p>Welcome to "Cooking for One". Get started by signing up or logging to manage your recipes.</p>
<% end %>

app/views/categories/index.html.erb
<% @categories.uniq.each do |c|%>

<p><%= link_to c.name, category_recipes_path(c) %></p>   

<% end %>

app/views/categories/show.html.erb
<%= @category.name %>



<h3>Recipes</h3>
<% @category.recipes do |r|%>

<%= link_to r.title, category_recipe_path(@category, r) %> 

<% end %>

app/views/layouts/_nav.html.erb
<div id="logo-wrapper">
    
    <h1>Cooking for one</h1>
   
    
</div>
<div class="topnav">
<%=link_to "Home", root_path%>
<% if !user_signed_in? %>
<%= link_to "Sign up", new_user_registration_path %>
<%= link_to "Login", new_user_session_path %>
<% else %>
<%= link_to 'All Recipes', recipes_path %>     
<%= link_to 'Courses',  categories_path%>     
<%= link_to 'Add a recipe',  new_recipe_path%>
<%= link_to "Log out",destroy_user_session_path, method: "delete" %>
<% end %>
</div>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooking for one</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <div class="wrapper">
    <header class="header">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <%= render "layouts/nav" %>
  </header>
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this recipe from being saved:
    </h2>
 
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @recipe do |f| %>
<br>

<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title %> <br>
</div>

<div class="form-group">
<%= f.label :cooking_time %>
<%= f.text_field :cooking_time %> <br>
</div>

<div class="form-group">
<%= f.label :instructions %><br>
<%= f.text_area :instructions %> 
</div>

<br>

<% if !@category%>
<p>Select an existing category</p>
<%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: true) %>

<p>Or create a new one</p>

<%= f.fields_for :category, @recipe.build_category  do |uf|%>
    
<%= uf.label :name  %>
<%= uf.text_field :name %>
<% end %>

<% else %>

<%= f.hidden_field :category_id%>

<% end %>

<%= f.submit "Submit" %>

<% end %>

app/views/recipes/edit.html.erb
<%= render "form" %>

app/views/recipes/filter_time.html.erb
<h3>Your recipe list</h3>
<br>
<p>Number of recipes: <%= @recipes.count %></p>
<ul>
<% @recipes.each do |r|%>
<li><%= r.category.name %>: <%= r.title %>-<%= r.created_at.strftime("%B %d, %Y") %></li>

<% end %>
</ul>

app/views/recipes/index.html.erb
<ul>
<% @recipes.each do |r| %>
<li><p><%= link_to r.category.name, category_recipes_path(r.category) %> - <%= link_to r.title, recipe_path(r) %></p> </li>
<p>more by <%= link_to r.user.username, user_recipes_path(r.user)%></p>
<% end %>
</ul>

<% if !@filter%>
<p>To see the list ordered alphabetically, Click <%= link_to 'Ordered list', recipes_ordered_list_path %></p>
<% end %>

<% if @category%>
<p><%= link_to 'Add a recipe to this category', new_category_recipe_path(@category) %></p>
<% end %>

app/views/recipes/new.html.erb
<%= render "form" %>

app/views/recipes/show.html.erb
 
 
 <h5><%= @recipe.title %></h5>
<p>by <%= @recipe.user.username %></p>

 <p>Cooking time: <%= @recipe.cooking_time %></p>


 <p>Instructions: <%= @recipe.instructions %></p>





 <p><%= link_to 'Edit', edit_recipe_path(@recipe) %></p>

 <p><%= link_to 'Delete', recipe_path(@recipe), data: { method: :delete } %></p>



 <h5>Reviews</h5>

 

 <%= form_for Review.new do |f| %>

<%= f.hidden_field :recipe_id, value: @recipe.id %>


 <%= f.label :heading %>
 <%= f.text_field :heading %>

 <%= f.label :description %>
 <%= f.text_field :description %>

 <%= f.submit %>

 <% end %>

<% @recipe.reviews.each do |r| %>
<div>
<h6><%= r.heading %></h6>
<p>by <%= r.user.username %> </p>
<p><%= r.description %></p>

</div>
<% end %>


 